### ISSUE TITLE
[feature] 로그인 UI - 소셜로그인 제외

### ISSUE THREAD

**Issue by JOYmet33** [ZZANTech/ZZANTech-Fe#1]
## 🚀 Description
로그인 UI 생성 (소셜로그인은 다른 이슈에서 다룰 예정이니 제외함)

## ✅ Todo
- [ ] 로그인 UI 뼈대 만들기
- [ ] 로그인 UI 로직 테스트 :  인풋
- [ ] 로그인 UI 로직 테스트 : 유효성 검사
- [ ] 로그인 UI 로직 테스트 : 버튼 막기
- [ ] 로그인 UI 로직 완성

## ⏰ 예상 소요 시간
2024-08-05 (월)
