### ISSUE TITLE
[feature] 짠 소비 상세 페이지 UI

### ISSUE THREAD

**Issue by Dayeon-Cheon** [ZZANTech/ZZANTech-Fe#131]
## 🚀 Description
짠 소비 상세 페이지 UI

## ✅ Todo
- [x] 짠 소비 상세 페이지 UI 구현
- [x] 제목란에 테스트용으로 넣어두었던 게시글 아이디 삭제
- [x] 네비게이션 버튼 항상 보이도록 수정
- [x] 짠 소비 작성일 표시

## ⏰ 예상 소요 시간
하루 이내
