### ISSUE TITLE
[feature] 회원가입 유효성 검사 추가

### ISSUE THREAD

**Issue by NHJeans** [ZZANTech/ZZANTech-Fe#132]
## 🚀 Description
- 회원가입 유효성 검사 및 UI 작업

## ✅ Todo
- [x] 유효성 검사 및 중복 체크 상태를 관리하는 로직 추가
- [x] 유효성 검사 결과에 따른 경고 및 성공 메시지 스타일링
- [x] 회원가입 피그마에 따른 스타일링 작업
- [x] 입력폼에 모든 내용을 채우지 않았을 경우와 채웠을 경우에 따른 버튼 색상 변경
