### ISSUE TITLE
[feature] 회원가입 UI

### ISSUE THREAD

**Issue by JOYmet33** [ZZANTech/ZZANTech-Fe#2]
## 🚀 Description
회원가입 UI 생성

## ✅ Todo
- [ ] 회원가입 UI 뼈대 만들기
- [ ] 회원가입 UI 로직 테스트 : 인풋 (handler 함수, 입력 반응)
- [ ] 회원가입 UI 로직 테스트 : 유효성 검사
- [ ] 회원가입 UI 로직 테스트 : 중복처리 (아이디, 닉네임)
- [ ] 회원가입 UI 로직 테스트 : 버튼 막기
- [ ] 회원가입 UI 로직 완성

## ⏰ 예상 소요 시간
2024-08-05 (월)
