### ISSUE TITLE
[feature] 채팅방내의 디테일한 ui수정

### ISSUE THREAD

**Issue by NHJeans** [ZZANTech/ZZANTech-Fe#222]
## 🚀 Description
- 채팅방내 디테일한 부분들 수정

## ✅ Todo
- [x] 사진 첨부시 보이는 미리보기창 수정
- [x] 사진 첨부하여 전송시 깔끔한 ui로 처리
- [x] 채팅방 리스트 부분 피그마대로 ui작업

## ⏰ 예상 소요 시간
1
