### ISSUE TITLE
[feature] 댓글 중복 제출 방지

### ISSUE THREAD

**Issue by Dayeon-Cheon** [ZZANTech/ZZANTech-Fe#227]
## 🚀 Description
댓글 중복 제출 방지

## ✅ Todo
- [x] 댓글 중복 제출 방지
- [x] 댓글 최신순 정렬
- [x] 짠 소비 내용 엔터 적용

## ⏰ 예상 소요 시간
하루 이내
