### ISSUE TITLE
[BUG] 짠 노하우 게시글 수정에서 기존이미지를 그대로 사용하여 수정 완료를 했을때 이미지 크기지정이 해제 되는문제

### ISSUE THREAD

**Issue by mangmuse** [ZZANTech/ZZANTech-Fe#252]
## 🐞 Description
(발생한 버그의 배경 및 현상 설명)
- 짠 노하우 상세페이지에서 CLS를 없애기 위해 이미지 크기를 지정해 줄 필요가 있었음 
- 일정한 이미지 크기를 지정해 줄 경우 이미지가 자연스럽지 못하고 깨지기 때문에 원본의 크기로 지정을 하고싶었음
- KnowhowEditor컴포넌트에서 글을 작성할때 img 태그에 width와 height을 지정하도록 설정
- 잘 작동 하는듯 하나 수정페이지에 가서 기존 이미지를 그대로 사용하면 이미지 크기지정이 깨져서 원본의 크기가 아닌 default값인 600x400으로 이미지가 보여짐

## 🔍 Steps to Reproduce
1. 짠 노하우 게시판에 이미지업로드 후 게시
![image](https://github.com/user-attachments/assets/3026e97c-cb2c-427e-a029-243a34796658)
(이미지가 원본크기로 나온다)
2. 작성한 글 상세페이지에 들어가서 수정버튼을 누르고 수정페이지에 진입
3. 그대로 수정 완료
![image](https://github.com/user-attachments/assets/b0cf352b-08db-4f3d-adc3-4769e15e487d)
4. 이미지 크기가 달라짐
![image](https://github.com/user-attachments/assets/621ac435-0c60-419e-a24c-89926ff89f98)
( 원본 이미지크기를 찾지 못해 default로 설정해둔 600*400 사이즈로 보여진다)

## 📝 Expected Behavior
이미지가 원본 사이즈를 유지해야함

💡 Possible Solution
수정 페이지에 들어왔을때 content의 img태그에는 width와 height항목이 있으나
submit을 할때 newKnowhow.content에는 width와 height 항목이 사라져있음(원인파악 못함)

## ✅ Todo

 - [ ] (구체적인 작업 목록을 작성해주세요)
 - [ ] 도중에
 - [ ] 예: API 인증 토큰 확인 로직 추가)
 - [ ] (예: 버그 수정 후 테스트)

2. 작성한 글 상세페이지에 들어가서 수정버튼을 누르고 수정페이지에 진입
3. 그대로 수정 완료
4. 이미지 크기가 달라짐

## 📝 Expected Behavior
이미지가 원본 사이즈를 유지해야함

💡 Possible Solution
수정 페이지에 들어왔을때 content의 img태그에는 width와 height항목이 있으나
submit을 할때 newKnowhow.content에는 width와 height 항목이 사라져있음(원인파악 못함)

## ✅ Todo

 - [ ] (구체적인 작업 목록을 작성해주세요)
 - [ ] 도중에
 - [ ] 예: API 인증 토큰 확인 로직 추가)
 - [ ] (예: 버그 수정 후 테스트)
