### ISSUE TITLE
[feature] 마이페이지 모바일 반응형 UI 구축

### ISSUE THREAD

**Issue by JOYmet33** [ZZANTech/ZZANTech-Fe#299]
## 🚀 Description
마이페이지 모바일 반응형 UI 구축

## ✅ Todo
- [x] info 영역 조정("비밀번호 변경" 버튼 등)
- [x] point 영역 조정("사용내역" 버튼 등)
- [x] 로그아웃 버튼 추가
- [x] 상단 "마이페이지" 헤더 추가

## ⏰ 예상 소요 시간
2024-08-17
