### ISSUE TITLE
[feature] header UI 작업

### ISSUE THREAD

**Issue by JOYmet33** [ZZANTech/ZZANTech-Fe#35]
## 🚀 Description
유저의 로그인 상태를 확인하는 방법으로 메인페이지 헤더의 작업을 먼저 시행하려 합니다.
(로그인 여부:  로그인 버튼 >> 마이프로필 버튼)

## ✅ Todo
- [x] <header> width, height 잡기
- [x] 각 버튼의 width, height, 정위치 잡기 : 로고, 홈, 짠-소비구경, 짠-노하우, 살까말까?live, 로그인/마이프로필
- [x] 스타일 입히기 : margin, padding, gap, border, border-color, text-bold, text-size 등
- [x] 각 버튼의 Link 경로 넣기 : 메인페이지, 마이프로필, 로그인, 짠-소비구경, 짠-노하우, 살까말까?live

## ⏰ 예상 소요 시간
2024. 7. 24.(수)
