### ISSUE TITLE
[feature] 짠 노하우 수정 및 삭제

### ISSUE THREAD

**Issue by mangmuse** [ZZANTech/ZZANTech-Fe#36]
## 🚀 Description
(현재 개발하고자 하는 기능의 배경 및 주 기능 간략 설명 (ex. 회원 관련 소셜 로그인 기능 구현)

## ✅ Todo
- [ ] 수정 페이지에서 기존 content 가져오기
- [ ] 수정 시에 image_urls 에 put으로 이미지 넣기
- [ ] 짠 노하우 게시글 수정
- [ ] 짠 노하우 게시글 삭제

## ⏰ 예상 소요 시간
1일 이내 ~ 2일
