### ISSUE TITLE
[feature/user] context API로 유저 상태관리

### ISSUE THREAD

**Issue by JOYmet33** [ZZANTech/ZZANTech-Fe#39]
## 🚀 Description
- 요구사항 : 게시글 좋아요 또는 투표, 오늘의 퀴즈 문제풀기 등 유저의 히스토리 필요
- context API로 유저의 상태관리

## ✅ Todo
- [ ] signin 라우트 핸들러 오류 해결 : 로그인 클릭하여도 쿠키가 저장되지 않는 오류가 있음
- [ ] context 폴더, UserContext.ts 파일 생성 
- [ ] LoginContainer 파일에서 useContext 작성: user 정보 저장

## ⏰ 예상 소요 시간
2024-07-24 (수)
