### ISSUE TITLE
[feature/quiz] 퀴즈 기능

### ISSUE THREAD

**Issue by NHJeans** [ZZANTech/ZZANTech-Fe#4]
## 🚀 Description
- 하루에 하나의 퀴즈만 풀수 있고 퀴즈를 풀고나면 퀴즈를 못 풀게 하기

## ✅ Todo
- [x] DB에 저장된 퀴즈 하루에 하나만 불러오게 하는 로직 작성
- [x] 퀴즈를 풀고 정답일 경우 일정 포인트 적립, 오답이라도 일정 포인트 적립 기능
- [ ] 퀴즈를 풀면 다른 UI로 보이게 작업

## ⏰ 예상 소요 시간
2일 소요 예정
