### ISSUE TITLE
[Etc/user] 전역 CSS 적용, 콘솔 삭제, 언급되지 않은 변수 및 임포트 삭제

### ISSUE THREAD

**Issue by JOYmet33** [ZZANTech/ZZANTech-Fe#47]
## 🚀 Description
유저 상태 관리를 하루 빨리 전달하다 보니 미세한 작업들을 놓쳐 이슈로 등록합니다.

## ✅ Todo
- [ ] 전역 CSS 적용 : 반복적으로 작성한 tailwind 코드를 전역 CSS(globasl.css)로 관리하여 변경사항이 있을 시 빠르게 변경하고, 깔끔한 코드로 가독성 향상
- [ ] 콘솔 삭제 : 통신 서버 오류를 잡기 위해 콘솔을 여기저기 찍었으나 오류를 해결하여 삭제
- [ ] 언급되지 않은 변수 및 임포트 삭제 : 지난 PR에서 많은 변경사항이 발생하여 사용하지 않는 변수나 임포트가 있어 삭제

## ⏰ 예상 소요 시간
2024-07-25 (목)
