### ISSUE TITLE
[feature] 마이페이지 UI

### ISSUE THREAD

**Issue by JOYmet33** [ZZANTech/ZZANTech-Fe#76]
## 🚀 Description
마이페이지 UI를 5가지로 나눠서 구성하고자 합니다.
1. 회원정보 : Info 폴더
2. 포인트 : Point 폴더
3. 등급 : Level 폴더
4. 게시글(내꺼) : MyPosts 폴더
5. 좋아요(남의꺼) : OtherPosts 폴더

## ✅ Todo
- [x] 폴더, 파일 등 컴포넌트별로 구성하기
- [x] #79
- [x] user 정보 입히기 : Info, Point, Level
- [x] 이벤트 함수 적용하기 (간단하게 다른 페이지로 이동하는 것도 포함)

## ⏰ 예상 소요 시간
2024-07-27 (토)
