### ISSUE TITLE
[feature] posts component

### ISSUE THREAD

**Issue by mangmuse** [ZZANTech/ZZANTech-Fe#9]
## 🚀 Description
(현재 개발하고자 하는 기능의 배경 및 주 기능 간략 설명 (ex. 회원 관련 소셜 로그인 기능 구현)

## ✅ Todo
- [x] vote, knowhow 게시글 경로구성
- [x] 댓글 컨테이너 컴포넌트 생성
- [x] 댓글 입력폼 컴포넌트 생성
- [x] 댓글 리스트 컴포넌트 생성
- [x] 댓글 아이템 컴포넌스 생성
