### ISSUE TITLE
[feature] 짠 소비 목록 무한 스크롤

### ISSUE THREAD

**Issue by Dayeon-Cheon** [ZZANTech/ZZANTech-Fe#95]
## 🚀 Description
짠 소비 목록 무한 스크롤

## ✅ Todo
- [x] 짠 소비 목록 UI
- [x] 짠 소비 더미 데이터 삽입
- [x] 짠 소비 목록 무한 스크롤 구현

## ⏰ 예상 소요 시간
하루 이내
