### ISSUE TITLE
[feature] 짠 소비 GOOD / BAD 데이터 저장 및 수정

### ISSUE THREAD

**Issue by Dayeon-Cheon** [ZZANTech/ZZANTech-Fe#99]
## 🚀 Description
짠 소비 GOOD / BAD 데이터 저장 및 수정

## ✅ Todo
- [ ] 버튼 처음 클릭시 DB에 데이터 저장
- [ ] 다른 버튼으로 변경시 DB에서 이전 데이터 값 수정
- [ ] 버튼 처음 클릭시 포인트 취득 처리

## ⏰ 예상 소요 시간
하루 이내
